### ISSUE TITLE
Tracking issue - transaction batching

### ISSUE THREAD

**Issue by alexspeller** [cardstack/sawtooth-git#1]
Goal: Allow batching multiple commits into a single transaction to reduce blockchain chatter

- [ ] Allow batching multiple commits into a single commit
  - [ ] New transaction type that is multiple commits instead of just one
  - [ ] Figure out how the list of commits and metadata are stored in that transaction type - probably off chain
  - [ ] Investigate git native packfiles or invent custom storage format
  - [ ] Design and implement rehydration from the batched commit data files
  - [ ] Store all data from the series of commits in a single blob, instead of using individual content-addressable objects
- [ ] Allow encrypting the data on S3
- [ ] Test with ipfs

**Comment by alexspeller** [comment]
Summary of the gitchain issue I'm thinking about at the moment:

So, we want to push bundled commits to the blockchain. So say we have a repo with 1000 commits.

So to avoid a push of that repo creating 1000 different transactions, we want to create a single transaction.

Transactions have a size limit, so we can't write all 1000 states to the blockchain in a single transaction.

So if you have commit 999, and you want to see if it's been written to the blockchain yet, you can't just look at `http://hyperledger/state/[state address of commit 9999]` because it will not have been written directly.

You also can't look at commit 1000 and see if the bundle contains all the other 999 shas you're interested in.

A solution to (1) is difficult. One solution might be to chunk commits instead of bundling them. So say we can fit ~100 shas in a transaction (varies depending on how we encode stuff and what other metadata we want to push). Now we only need to push 10 commits instead of 1000, which is definitely an improvement. It keeps the blockchain state accurate with an entry for each commit whilst only pushing 10 transactions.

A solution to (2) might be easier. I'm looking at implementing a bloom filter so that you can look at a transaction to see what commits it (probably) refers to. If there is a false positive, then that's fine as it can be explicitly verified later.

I think these solutions are, however, mutually exclusive. If we are putting a (limited) number of shas in a commit, we don't need a bloom filter (and it wouldn't even fit, as we're using the space budget to list the shas anyway).

So I'm leaning towards the chunking approach as it allows for the blockchain state to remain accurate, even though it doesn't meet the requirement to allow any arbitrary sized repo to be pushed into a single blockchain transaction.

Any thoughts?

**Comment by ef4** [comment]
I don't know what your priority is for ipfs or s3, but I think that is fundamental to this design question. Ideally the blockchain is just for pointing to the newest head.

**Comment by alexspeller** [comment]
Summary of latest thinking: Transactions are 1:1 with pushes instead of commits. Push updates a state address that represents a tag.
